name: Deploy S3 Bucket (CloudFormation)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "infra/**"
      - ".github/workflows/deploy.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::951138415960:role/GitHubActions-DeployS3
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name mentor-s3-demo \
            --template-file infra/s3-bucket.yml \
            --no-fail-on-empty-changeset
